// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Reserva
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reservaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Reserva";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Valor("Valor"),
		Desconto("Desconto"),
		Data("Data"),
		Numero("Numero"),
		Reserva_Viagem("MyFirstModule.Reserva_Viagem"),
		Reserva_Passageiro("MyFirstModule.Reserva_Passageiro");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Reserva(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Reserva"));
	}

	protected Reserva(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reservaMendixObject)
	{
		if (reservaMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Reserva", reservaMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Reserva");

		this.reservaMendixObject = reservaMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Reserva.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Reserva initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Reserva.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Reserva initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Reserva(context, mendixObject);
	}

	public static myfirstmodule.proxies.Reserva load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Reserva.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Reserva> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Reserva> result = new java.util.ArrayList<myfirstmodule.proxies.Reserva>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Reserva" + xpathConstraint))
			result.add(myfirstmodule.proxies.Reserva.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Valor
	 */
	public final java.math.BigDecimal getValor()
	{
		return getValor(getContext());
	}

	/**
	 * @param context
	 * @return value of Valor
	 */
	public final java.math.BigDecimal getValor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Valor.toString());
	}

	/**
	 * Set value of Valor
	 * @param valor
	 */
	public final void setValor(java.math.BigDecimal valor)
	{
		setValor(getContext(), valor);
	}

	/**
	 * Set value of Valor
	 * @param context
	 * @param valor
	 */
	public final void setValor(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal valor)
	{
		getMendixObject().setValue(context, MemberNames.Valor.toString(), valor);
	}

	/**
	 * @return value of Desconto
	 */
	public final java.lang.Integer getDesconto()
	{
		return getDesconto(getContext());
	}

	/**
	 * @param context
	 * @return value of Desconto
	 */
	public final java.lang.Integer getDesconto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Desconto.toString());
	}

	/**
	 * Set value of Desconto
	 * @param desconto
	 */
	public final void setDesconto(java.lang.Integer desconto)
	{
		setDesconto(getContext(), desconto);
	}

	/**
	 * Set value of Desconto
	 * @param context
	 * @param desconto
	 */
	public final void setDesconto(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer desconto)
	{
		getMendixObject().setValue(context, MemberNames.Desconto.toString(), desconto);
	}

	/**
	 * @return value of Data
	 */
	public final java.util.Date getData()
	{
		return getData(getContext());
	}

	/**
	 * @param context
	 * @return value of Data
	 */
	public final java.util.Date getData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Data.toString());
	}

	/**
	 * Set value of Data
	 * @param data
	 */
	public final void setData(java.util.Date data)
	{
		setData(getContext(), data);
	}

	/**
	 * Set value of Data
	 * @param context
	 * @param data
	 */
	public final void setData(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date data)
	{
		getMendixObject().setValue(context, MemberNames.Data.toString(), data);
	}

	/**
	 * @return value of Numero
	 */
	public final java.lang.Long getNumero()
	{
		return getNumero(getContext());
	}

	/**
	 * @param context
	 * @return value of Numero
	 */
	public final java.lang.Long getNumero(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Numero.toString());
	}

	/**
	 * Set value of Numero
	 * @param numero
	 */
	public final void setNumero(java.lang.Long numero)
	{
		setNumero(getContext(), numero);
	}

	/**
	 * Set value of Numero
	 * @param context
	 * @param numero
	 */
	public final void setNumero(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long numero)
	{
		getMendixObject().setValue(context, MemberNames.Numero.toString(), numero);
	}

	/**
	 * @return value of Reserva_Viagem
	 */
	public final myfirstmodule.proxies.Viagem getReserva_Viagem() throws com.mendix.core.CoreException
	{
		return getReserva_Viagem(getContext());
	}

	/**
	 * @param context
	 * @return value of Reserva_Viagem
	 */
	public final myfirstmodule.proxies.Viagem getReserva_Viagem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Viagem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Reserva_Viagem.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Viagem.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Reserva_Viagem
	 * @param reserva_viagem
	 */
	public final void setReserva_Viagem(myfirstmodule.proxies.Viagem reserva_viagem)
	{
		setReserva_Viagem(getContext(), reserva_viagem);
	}

	/**
	 * Set value of Reserva_Viagem
	 * @param context
	 * @param reserva_viagem
	 */
	public final void setReserva_Viagem(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Viagem reserva_viagem)
	{
		if (reserva_viagem == null)
			getMendixObject().setValue(context, MemberNames.Reserva_Viagem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Reserva_Viagem.toString(), reserva_viagem.getMendixObject().getId());
	}

	/**
	 * @return value of Reserva_Passageiro
	 */
	public final myfirstmodule.proxies.Passageiro getReserva_Passageiro() throws com.mendix.core.CoreException
	{
		return getReserva_Passageiro(getContext());
	}

	/**
	 * @param context
	 * @return value of Reserva_Passageiro
	 */
	public final myfirstmodule.proxies.Passageiro getReserva_Passageiro(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Passageiro result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Reserva_Passageiro.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Passageiro.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Reserva_Passageiro
	 * @param reserva_passageiro
	 */
	public final void setReserva_Passageiro(myfirstmodule.proxies.Passageiro reserva_passageiro)
	{
		setReserva_Passageiro(getContext(), reserva_passageiro);
	}

	/**
	 * Set value of Reserva_Passageiro
	 * @param context
	 * @param reserva_passageiro
	 */
	public final void setReserva_Passageiro(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Passageiro reserva_passageiro)
	{
		if (reserva_passageiro == null)
			getMendixObject().setValue(context, MemberNames.Reserva_Passageiro.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Reserva_Passageiro.toString(), reserva_passageiro.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reservaMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Reserva that = (myfirstmodule.proxies.Reserva) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Reserva";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
