// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Viagem
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject viagemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Viagem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Data("Data"),
		Valor("Valor"),
		Viagem_Veiculo("MyFirstModule.Viagem_Veiculo"),
		Viagem_Localidade_Origem("MyFirstModule.Viagem_Localidade_Origem"),
		Viagem_Localidade_Destino("MyFirstModule.Viagem_Localidade_Destino"),
		Viagem_Motorista("MyFirstModule.Viagem_Motorista");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Viagem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Viagem"));
	}

	protected Viagem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject viagemMendixObject)
	{
		if (viagemMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Viagem", viagemMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Viagem");

		this.viagemMendixObject = viagemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Viagem.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Viagem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Viagem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Viagem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Viagem(context, mendixObject);
	}

	public static myfirstmodule.proxies.Viagem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Viagem.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Viagem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Viagem> result = new java.util.ArrayList<myfirstmodule.proxies.Viagem>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Viagem" + xpathConstraint))
			result.add(myfirstmodule.proxies.Viagem.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Data
	 */
	public final java.util.Date getData()
	{
		return getData(getContext());
	}

	/**
	 * @param context
	 * @return value of Data
	 */
	public final java.util.Date getData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Data.toString());
	}

	/**
	 * Set value of Data
	 * @param data
	 */
	public final void setData(java.util.Date data)
	{
		setData(getContext(), data);
	}

	/**
	 * Set value of Data
	 * @param context
	 * @param data
	 */
	public final void setData(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date data)
	{
		getMendixObject().setValue(context, MemberNames.Data.toString(), data);
	}

	/**
	 * @return value of Valor
	 */
	public final java.math.BigDecimal getValor()
	{
		return getValor(getContext());
	}

	/**
	 * @param context
	 * @return value of Valor
	 */
	public final java.math.BigDecimal getValor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Valor.toString());
	}

	/**
	 * Set value of Valor
	 * @param valor
	 */
	public final void setValor(java.math.BigDecimal valor)
	{
		setValor(getContext(), valor);
	}

	/**
	 * Set value of Valor
	 * @param context
	 * @param valor
	 */
	public final void setValor(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal valor)
	{
		getMendixObject().setValue(context, MemberNames.Valor.toString(), valor);
	}

	/**
	 * @return value of Viagem_Veiculo
	 */
	public final myfirstmodule.proxies.Veiculo getViagem_Veiculo() throws com.mendix.core.CoreException
	{
		return getViagem_Veiculo(getContext());
	}

	/**
	 * @param context
	 * @return value of Viagem_Veiculo
	 */
	public final myfirstmodule.proxies.Veiculo getViagem_Veiculo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Veiculo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Viagem_Veiculo.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Veiculo.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Viagem_Veiculo
	 * @param viagem_veiculo
	 */
	public final void setViagem_Veiculo(myfirstmodule.proxies.Veiculo viagem_veiculo)
	{
		setViagem_Veiculo(getContext(), viagem_veiculo);
	}

	/**
	 * Set value of Viagem_Veiculo
	 * @param context
	 * @param viagem_veiculo
	 */
	public final void setViagem_Veiculo(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Veiculo viagem_veiculo)
	{
		if (viagem_veiculo == null)
			getMendixObject().setValue(context, MemberNames.Viagem_Veiculo.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Viagem_Veiculo.toString(), viagem_veiculo.getMendixObject().getId());
	}

	/**
	 * @return value of Viagem_Localidade_Origem
	 */
	public final myfirstmodule.proxies.Localidade getViagem_Localidade_Origem() throws com.mendix.core.CoreException
	{
		return getViagem_Localidade_Origem(getContext());
	}

	/**
	 * @param context
	 * @return value of Viagem_Localidade_Origem
	 */
	public final myfirstmodule.proxies.Localidade getViagem_Localidade_Origem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Localidade result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Viagem_Localidade_Origem.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Localidade.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Viagem_Localidade_Origem
	 * @param viagem_localidade_origem
	 */
	public final void setViagem_Localidade_Origem(myfirstmodule.proxies.Localidade viagem_localidade_origem)
	{
		setViagem_Localidade_Origem(getContext(), viagem_localidade_origem);
	}

	/**
	 * Set value of Viagem_Localidade_Origem
	 * @param context
	 * @param viagem_localidade_origem
	 */
	public final void setViagem_Localidade_Origem(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Localidade viagem_localidade_origem)
	{
		if (viagem_localidade_origem == null)
			getMendixObject().setValue(context, MemberNames.Viagem_Localidade_Origem.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Viagem_Localidade_Origem.toString(), viagem_localidade_origem.getMendixObject().getId());
	}

	/**
	 * @return value of Viagem_Localidade_Destino
	 */
	public final myfirstmodule.proxies.Localidade getViagem_Localidade_Destino() throws com.mendix.core.CoreException
	{
		return getViagem_Localidade_Destino(getContext());
	}

	/**
	 * @param context
	 * @return value of Viagem_Localidade_Destino
	 */
	public final myfirstmodule.proxies.Localidade getViagem_Localidade_Destino(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Localidade result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Viagem_Localidade_Destino.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Localidade.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Viagem_Localidade_Destino
	 * @param viagem_localidade_destino
	 */
	public final void setViagem_Localidade_Destino(myfirstmodule.proxies.Localidade viagem_localidade_destino)
	{
		setViagem_Localidade_Destino(getContext(), viagem_localidade_destino);
	}

	/**
	 * Set value of Viagem_Localidade_Destino
	 * @param context
	 * @param viagem_localidade_destino
	 */
	public final void setViagem_Localidade_Destino(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Localidade viagem_localidade_destino)
	{
		if (viagem_localidade_destino == null)
			getMendixObject().setValue(context, MemberNames.Viagem_Localidade_Destino.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Viagem_Localidade_Destino.toString(), viagem_localidade_destino.getMendixObject().getId());
	}

	/**
	 * @return value of Viagem_Motorista
	 */
	public final myfirstmodule.proxies.Motorista getViagem_Motorista() throws com.mendix.core.CoreException
	{
		return getViagem_Motorista(getContext());
	}

	/**
	 * @param context
	 * @return value of Viagem_Motorista
	 */
	public final myfirstmodule.proxies.Motorista getViagem_Motorista(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Motorista result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Viagem_Motorista.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Motorista.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Viagem_Motorista
	 * @param viagem_motorista
	 */
	public final void setViagem_Motorista(myfirstmodule.proxies.Motorista viagem_motorista)
	{
		setViagem_Motorista(getContext(), viagem_motorista);
	}

	/**
	 * Set value of Viagem_Motorista
	 * @param context
	 * @param viagem_motorista
	 */
	public final void setViagem_Motorista(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Motorista viagem_motorista)
	{
		if (viagem_motorista == null)
			getMendixObject().setValue(context, MemberNames.Viagem_Motorista.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Viagem_Motorista.toString(), viagem_motorista.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return viagemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Viagem that = (myfirstmodule.proxies.Viagem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Viagem";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
